name: Auto Retrain Model

on:
  schedule:
    - cron: "0 0 * * 1"   # Every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run retraining script
      run: python retrain.py
